baseURL: 'https://yin123-ybh.github.io/'
languageCode: 'zh-cn'
title: 'Cecilia-塞西莉娅'
theme: 'hugo-theme-stack'

params:
  # 主题配置
  title: 'Cecilia-塞西莉娅'
  description: 'Welcome to my website'
  
  # 头像配置
  avatar:
    local: true
    src: 'img/avatar.png'
  
  # 社交链接
  social:
    - name: 'GitHub'
      icon: 'brand-github'
      url: 'https://github.com/yin123-ybh'
    - name: 'Twitter'
      icon: 'brand-twitter'
      url: 'https://twitter.com/yourusername'
  
  # 菜单配置
  menu:
    main:
      - identifier: 'home'
        name: 'Home'
        url: '/'
        weight: 10
      - identifier: 'about'
        name: 'About'
        url: '/about/'
        weight: 20
      - identifier: 'archives'
        name: 'Archives'
        url: '/archives/'
        weight: 30
      - identifier: 'search'
        name: 'Search'
        url: '/search/'
        weight: 40
      - identifier: 'links'
        name: 'Links'
        url: '/links/'
        weight: 50

# 构建配置
buildDrafts: false
buildFuture: false
buildExpired: false
